select
    window_start,
    cast(null as Nullable(String)) as org,
    gateway,
    region,
    pipeline_id,
    model_id,
    sessions_count,
    avg_output_fps,
    total_minutes,
    known_sessions_count,
    served_sessions,
    unserved_sessions,
    total_demand_sessions,
    startup_unexcused_sessions,
    confirmed_swapped_sessions,
    inferred_swap_sessions,
    total_swapped_sessions,
    sessions_ending_in_error,
    error_status_samples,
    health_signal_coverage_ratio,
    startup_success_rate,
    effective_success_rate,
    ticket_face_value_eth
from {{ ref('v_api_network_demand_by_org') }}
