select
    window_start,
    cast(null as Nullable(String)) as org,
    orchestrator_address,
    pipeline_id,
    model_id,
    gpu_id,
    region,
    known_sessions_count,
    startup_success_sessions,
    startup_excused_sessions,
    startup_unexcused_sessions,
    confirmed_swapped_sessions,
    inferred_swap_sessions,
    total_swapped_sessions,
    sessions_ending_in_error,
    error_status_samples,
    health_signal_coverage_ratio,
    startup_success_rate,
    effective_success_rate,
    no_swap_rate,
    sla_score
from {{ ref('v_api_sla_compliance_by_org') }}
