apiVersion: 1

contactPoints:
  - orgId: 1
    name: naap-default-warning
    receivers:
      - uid: naap_discord_warning
        type: discord
        disableResolveMessage: true
        settings:
          url: ${GRAFANA_ALERT_DISCORD_WEBHOOK_URL}
          use_discord_username: false
          message: |
            {{ template "naap.default.message" . }}
  - orgId: 1
    name: naap-critical-fanout
    receivers:
      - uid: naap_discord_critical
        type: discord
        disableResolveMessage: true
        settings:
          url: ${GRAFANA_ALERT_DISCORD_WEBHOOK_URL}
          use_discord_username: false
          message: |
            {{ template "naap.default.message" . }}
      - uid: naap_telegram_critical
        type: telegram
        disableResolveMessage: true
        settings:
          bottoken: ${GRAFANA_ALERT_TELEGRAM_BOT_TOKEN}
          chatid: ${GRAFANA_ALERT_TELEGRAM_CHAT_ID}
          message: |
            {{ template "naap.default.message" . }}
