with {{ latest_value_cte('latest_sessions', 'naap.canonical_session_current_store', ['org', 'canonical_session_key'], 'materialized_at', 'materialized_at') }}
select
    s.canonical_session_key,
    s.org,
    s.stream_id,
    s.request_id,
    s.current_selection_event_id,
    s.current_selection_ts,
    s.canonical_pipeline,
    s.canonical_model,
    s.gpu_id,
    s.started_at,
    s.last_seen,
    s.startup_latency_ms,
    s.e2e_latency_ms,
    s.prompt_to_playable_latency_ms,
    s.requested_seen,
    cast(s.requested_seen, 'UInt8') as started,
    s.playable_seen,
    s.selection_outcome,
    cast(s.selection_outcome = 'no_orch', 'UInt8') as no_orch,
    s.completed,
    s.swap_count,
    s.restart_seen,
    s.error_seen,
    s.degraded_input_seen,
    s.degraded_inference_seen,
    s.status_sample_count,
    s.status_error_sample_count,
    s.startup_error_count,
    s.excusable_error_count,
    s.loading_only_session,
    s.zero_output_fps_session,
    s.health_signal_count,
    s.health_expected_signal_count,
    s.health_signal_coverage_ratio,
    s.startup_outcome as resolver_startup_outcome,
    multiIf(
        s.startup_outcome = 'success', 'success',
        s.startup_outcome = 'failed' and s.excusal_reason != 'none', 'excused',
        s.startup_outcome = 'failed', 'unexcused',
        s.startup_outcome
    ) as startup_outcome,
    s.excusal_reason,
    s.has_ambiguous_identity,
    s.has_snapshot_match,
    s.is_hardware_less,
    s.is_stale,
    s.attribution_reason,
    s.attribution_status,
    s.attributed_orch_address,
    s.attributed_orch_uri,
    s.attribution_snapshot_ts
from naap.canonical_session_current_store s
inner join latest_sessions l
    on {{ join_on_columns('s', 'l', ['org', 'canonical_session_key']) }}
   and s.materialized_at = l.materialized_at
