select
    canonical_session_key,
    org,
    stream_id,
    request_id,
    canonical_pipeline,
    canonical_model,
    started_at,
    last_seen,
    startup_latency_ms,
    e2e_latency_ms,
    prompt_to_playable_latency_ms,
    CAST(requested_seen, 'UInt8') as started,
    playable_seen,
    CAST(selection_outcome = 'no_orch', 'UInt8') as no_orch,
    completed,
    swap_count,
    restart_seen,
    error_seen,
    degraded_input_seen,
    degraded_inference_seen,
    status_sample_count,
    status_error_sample_count,
    startup_error_count,
    excusable_error_count,
    loading_only_session,
    zero_output_fps_session,
    health_signal_count,
    health_expected_signal_count,
    health_signal_coverage_ratio,
    multiIf(
        startup_outcome = 'success', 'success',
        startup_outcome = 'failed' and excusal_reason != 'none', 'excused',
        startup_outcome = 'failed', 'unexcused',
        'unknown'
    ) as startup_outcome,
    has_ambiguous_identity,
    has_snapshot_match,
    is_hardware_less,
    is_stale,
    attribution_reason,
    attribution_status,
    attributed_orch_address,
    attributed_orch_uri,
    attribution_snapshot_ts
from (
    select
        canonical_session_key,
        org,
        stream_id,
        request_id,
        canonical_pipeline,
        canonical_model,
        started_at,
        last_seen,
        startup_latency_ms,
        e2e_latency_ms,
        prompt_to_playable_latency_ms,
        requested_seen,
        playable_seen,
        selection_outcome,
        completed,
        swap_count,
        restart_seen,
        error_seen,
        degraded_input_seen,
        degraded_inference_seen,
        status_sample_count,
        status_error_sample_count,
        startup_error_count,
        excusable_error_count,
        loading_only_session,
        zero_output_fps_session,
        health_signal_count,
        health_expected_signal_count,
        health_signal_coverage_ratio,
        startup_outcome,
        excusal_reason,
        has_ambiguous_identity,
        has_snapshot_match,
        is_hardware_less,
        is_stale,
        attribution_reason,
        attribution_status,
        attributed_orch_address,
        attributed_orch_uri,
        attribution_snapshot_ts
    from naap.canonical_session_current_store
    order by org, canonical_session_key, materialized_at desc
)
limit 1 by canonical_session_key
